services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}

  frontend:
    restart: unless-stopped
